import { Anton, Oswald, Quicksand } from 'next/font/google';
import "./globals.css";
import VisitTracker from './components/VisitTracker';

const anton = Anton({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-anton',
});

const oswald = Oswald({
  weight: ['200', '300', '400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-oswald',
});

const quicksand = Quicksand({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-quicksand',
});

export const metadata = {
  title: "Trek Manthan Adventures",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.jpeg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${anton.variable} ${oswald.variable} ${quicksand.variable}`}>
        <VisitTracker />
        {children}
      </body>
    </html>
  );
}
